// Package issue1306 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v0.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue1306

// SomeType defines parameters for ExampleGet.
type SomeType struct {
	Name    *string          `json:"name,omitempty"`
	Objects *[]SomeChildType `json:"objects,omitempty"`
}

// SomeChildType defines parameters for ExampleGet.
type SomeChildType struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}
